version: '3.9'

services:
  GoTogether:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    networks:
      - GoTogether
networks:
  GoTogether:
    external: true
